---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - git
      - build-essential
      - unzip
      - wget
      - ca-certificates
      - software-properties-common
      - gnupg
    state: present
